mongodb:
  image: mongo:latest
  container_name: mongodb
  command: mongod --smallfiles
  ports:
   - "27017:27017"
  volumes:
   - ./mongo:/data/db:rw
  volume_driver: local
hygieia-api:
  image: hygieia-api:latest
  container_name: hygieia-api
  ports:
  - "8080:8080"
  volumes:
  - ./logs:/hygieia/logs
  links:
  - mongodb:mongo
hygieia-ui:
  image: hygieia-ui:latest
  container_name: hygieia-ui
  ports:
  - "8088:80"
  links:
  - hygieia-api
hygieia-github-scm-collector:
  image: hygieia-github-scm-collector:latest
  container_name: hygieia-github-scm-collector
  volumes:
  - ./logs:/hygieia/logs
  links:
  - hygieia-api
  - mongodb:mongo
